[workspace]
resolver = "2"
members = [
  "crates/c41-sys",
  "crates/c41-core",
  "crates/c41-db",
  "crates/c41-ui",
  "crates/c41",
]

[workspace.dependencies]
anyhow       = "1"
rayon        = "1"
rusqlite     = { version = "0.31", features = ["bundled"] }
tracing      = "0.1"
walkdir      = "2"
c41-sys  = { path = "crates/c41-sys" }
c41-core = { path = "crates/c41-core" }
c41-db   = { path = "crates/c41-db" }
c41-ui   = { path = "crates/c41-ui" }

[profile.release]
opt-level = 3
lto       = "thin"
strip     = true
