//! Hand-written FFI bindings to **libgphoto2** (tethered camera capture,
//! `pkg-config libgphoto2`).
//!
//! Kept out of `bindings.rs` on purpose, same as `lensfun.rs`: that file is
//! regenerated by bindgen from `src/common/darktable.h` and knows nothing
//! about gphoto2 — a regeneration would silently drop anything written there.
//!
//! Only the slice of the API the capture path consumes is declared, mirroring
//! what `src/common/camera_control.c` uses: context lifecycle, the port and
//! abilities setup plus open sequence of `_camera_initialize`, the capture to
//! file_get sequence of the `_JOB_TYPE_EXECUTE_CAPTURE` job, and the
//! autodetect list for camera detection. No burst, timelapse, live view,
//! config widgets, or filesystem browsing.
//!
//! Layout evidence (verified 2026-09-24 against upstream
//! `gphoto/libgphoto2` headers, noble ships 2.5.31 where these are stable):
//! - `CameraFilePath` is `name[128]` FIRST then `folder[1024]` — note the
//!   folder is 1024 bytes, not 128. Evidence: `gphoto2-camera.h` declares
//!   `char name [128]` then `char folder [1024]`, and `camera_control.c:323`
//!   passes `fp.folder, fp.name` positionally to `gp_camera_file_get`
//!   (folder first), which only type-checks with distinct members.
//!   MUST-VERIFY-BY-HEADER: the main session checks
//!   `/usr/include/gphoto2/gphoto2-camera.h` in Docker during the gate.
//! - `CameraAbilities` field order mirrors `gphoto2-abilities-list.h` exactly:
//!   model[128], status, port, speed[64], operations, file_operations,
//!   folder_operations, usb_vendor, usb_product, usb_class, usb_subclass,
//!   usb_protocol, library[1024], id[1024], device_type, reserved2..8.
//!   The enum-typed fields are plain `c_int` (C enums without fixed width).
//!   MUST-VERIFY-BY-HEADER against `gphoto2-abilities-list.h` in the gate.
//! - `GPPortInfo` is already a pointer (`typedef struct _GPPortInfo
//!   *GPPortInfo` in `gphoto2-port-info-list.h`), so it is a pointer type
//!   here too — no layout to verify.
//! - `GP_CAPTURE_IMAGE` is 0 (first enumerator of `CameraCaptureType`);
//!   `GP_FILE_TYPE_NORMAL` is 1 (second enumerator of `CameraFileType`,
//!   after `GP_FILE_TYPE_PREVIEW`); `GP_OK` is 0 with negative error codes.
//! - `gp_camera_free` and `gp_list_free` both exist in the headers (alongside
//!   the ref/unref variants darktable itself uses).

#![allow(non_snake_case, non_camel_case_types)]

use std::ffi::{c_char, c_int};

// ── Result + capture constants ───────────────────────────────────────────────

/// Success (`GP_OK == 0`); every error code is negative.
pub const GP_OK: c_int = 0;

/// Capture a still image (first enumerator of `CameraCaptureType`).
pub const GP_CAPTURE_IMAGE: c_int = 0;

/// The regular file data (second enumerator of `CameraFileType`).
pub const GP_FILE_TYPE_NORMAL: c_int = 1;

// ── Opaque handles ───────────────────────────────────────────────────────────

#[repr(C)]
pub struct Camera {
    _opaque: [u8; 0],
}

#[repr(C)]
pub struct GPContext {
    _opaque: [u8; 0],
}

#[repr(C)]
pub struct CameraFile {
    _opaque: [u8; 0],
}

#[repr(C)]
pub struct CameraList {
    _opaque: [u8; 0],
}

#[repr(C)]
pub struct CameraAbilitiesList {
    _opaque: [u8; 0],
}

#[repr(C)]
pub struct GPPortInfoList {
    _opaque: [u8; 0],
}

#[repr(C)]
pub struct GPPortInfoInner {
    _opaque: [u8; 0],
}

/// `GPPortInfo` is a pointer type in C (`typedef struct _GPPortInfo
/// *GPPortInfo`), so it is one here too.
pub type GPPortInfo = *mut GPPortInfoInner;

// ── Value structs (field order verified against upstream headers) ────────────

/// `CameraFilePath`: `name[128]` FIRST, then `folder[1024]`. See the module
/// doc for the header evidence; the gate re-verifies this order.
#[repr(C)]
pub struct CameraFilePath {
    pub name: [c_char; 128],
    pub folder: [c_char; 1024],
}

/// `CameraAbilities` prefix through the trailing reserved ints, in header
/// order. `gp_camera_set_abilities` takes this struct by value, so the full
/// width matters — the gate re-verifies it.
#[repr(C)]
pub struct CameraAbilities {
    pub model: [c_char; 128],
    pub status: c_int,
    pub port: c_int,
    pub speed: [c_int; 64],
    pub operations: c_int,
    pub file_operations: c_int,
    pub folder_operations: c_int,
    pub usb_vendor: c_int,
    pub usb_product: c_int,
    pub usb_class: c_int,
    pub usb_subclass: c_int,
    pub usb_protocol: c_int,
    pub library: [c_char; 1024],
    pub id: [c_char; 1024],
    pub device_type: c_int,
    pub reserved2: c_int,
    pub reserved3: c_int,
    pub reserved4: c_int,
    pub reserved5: c_int,
    pub reserved6: c_int,
    pub reserved7: c_int,
    pub reserved8: c_int,
}

// ── Context lifecycle ────────────────────────────────────────────────────────

extern "C" {
    pub fn gp_context_new() -> *mut GPContext;
    pub fn gp_context_unref(context: *mut GPContext);
}

// ── Camera lifecycle + open sequence (mirrors `_camera_initialize`) ──────────

extern "C" {
    pub fn gp_camera_new(camera: *mut *mut Camera) -> c_int;
    pub fn gp_camera_free(camera: *mut Camera) -> c_int;
    pub fn gp_camera_unref(camera: *mut Camera) -> c_int;
    pub fn gp_camera_init(camera: *mut Camera, context: *mut GPContext) -> c_int;
    pub fn gp_camera_exit(camera: *mut Camera, context: *mut GPContext) -> c_int;

    pub fn gp_camera_set_abilities(camera: *mut Camera, abilities: CameraAbilities) -> c_int;
    pub fn gp_camera_set_port_info(camera: *mut Camera, info: GPPortInfo) -> c_int;

    pub fn gp_abilities_list_new(list: *mut *mut CameraAbilitiesList) -> c_int;
    pub fn gp_abilities_list_free(list: *mut CameraAbilitiesList) -> c_int;
    pub fn gp_abilities_list_load(list: *mut CameraAbilitiesList, context: *mut GPContext) -> c_int;
    pub fn gp_abilities_list_lookup_model(list: *mut CameraAbilitiesList, model: *const c_char) -> c_int;
    pub fn gp_abilities_list_get_abilities(
        list: *mut CameraAbilitiesList,
        index: c_int,
        abilities: *mut CameraAbilities,
    ) -> c_int;

    pub fn gp_port_info_list_new(list: *mut *mut GPPortInfoList) -> c_int;
    pub fn gp_port_info_list_free(list: *mut GPPortInfoList) -> c_int;
    pub fn gp_port_info_list_load(list: *mut GPPortInfoList) -> c_int;
    pub fn gp_port_info_list_lookup_path(list: *mut GPPortInfoList, path: *const c_char) -> c_int;
    pub fn gp_port_info_list_get_info(
        list: *mut GPPortInfoList,
        n: c_int,
        info: *mut GPPortInfo,
    ) -> c_int;
}

// ── Capture + download (mirrors the `_JOB_TYPE_EXECUTE_CAPTURE` job) ─────────

extern "C" {
    pub fn gp_camera_capture(
        camera: *mut Camera,
        capture_type: c_int,
        path: *mut CameraFilePath,
        context: *mut GPContext,
    ) -> c_int;
    pub fn gp_camera_file_get(
        camera: *mut Camera,
        folder: *const c_char,
        file: *const c_char,
        data_type: c_int,
        camera_file: *mut CameraFile,
        context: *mut GPContext,
    ) -> c_int;

    pub fn gp_file_new(file: *mut *mut CameraFile) -> c_int;
    pub fn gp_file_free(file: *mut CameraFile) -> c_int;
    pub fn gp_file_save(file: *mut CameraFile, filename: *const c_char) -> c_int;
}

// ── Detection list ───────────────────────────────────────────────────────────

extern "C" {
    pub fn gp_camera_autodetect(list: *mut CameraList, context: *mut GPContext) -> c_int;

    pub fn gp_list_new(list: *mut *mut CameraList) -> c_int;
    pub fn gp_list_free(list: *mut CameraList) -> c_int;
    pub fn gp_list_count(list: *mut CameraList) -> c_int;
    pub fn gp_list_get_name(list: *mut CameraList, index: c_int, name: *mut *const c_char) -> c_int;
    pub fn gp_list_get_value(list: *mut CameraList, index: c_int, value: *mut *const c_char) -> c_int;
}

// ── Errors ───────────────────────────────────────────────────────────────────

extern "C" {
    pub fn gp_result_as_string(result: c_int) -> *const c_char;
}
