//! Hand-written FFI bindings to **liblensfun** (the reference C library for
//! lens distortion/TCA/vignetting correction, `pkg-config lensfun`).
//!
//! Kept out of `bindings.rs` on purpose: that file is regenerated by bindgen
//! from `src/common/darktable.h` and knows nothing about lensfun — a
//! regeneration would silently drop anything written there. This module is
//! committed, reviewed, and stable against regeneration.
//!
//! Only the slice of the API the Rust pipeline consumes is declared, mirroring
//! what `src/iop/lens.cc` uses. Structs carry the data-member prefix of the C
//! definitions (the trailing C++ methods occupy no storage); the library
//! allocates every object we touch, so a shorter Rust mirror of a longer C
//! struct is safe for prefix reads.
//!
//! Data model notes:
//! - Returned lists (`lf_db_find_cameras*`, `lf_db_find_lenses_hd`) are
//!   NULL-terminated arrays allocated by each call and released by the caller
//!   with [`lf_free`] — free the *array* only, never the elements, which stay
//!   owned by the database.
//! - `lfMLstr` fields are plain `char *` (the multi-language machinery is a
//!   C++-side convenience).

#![allow(non_snake_case, non_camel_case_types)]

use std::ffi::c_char;

/// `enum lfError`: LF_NO_ERROR == 0. Positive values are the enum codes below;
/// negative return values from lensfun entry points are `-errno`.
pub type lfError = i32;

/// No error occurred (`LF_NO_ERROR`).
pub const LF_NO_ERROR: lfError = 0;

/// Wrong XML data format (`LF_WRONG_FORMAT`, enum value 1).
pub const LF_WRONG_FORMAT: lfError = 1;

/// No database could be loaded (`LF_NO_DATABASE`, enum value 2) — the usual
/// result of missing data files rather than a hard failure for us.
pub const LF_NO_DATABASE: lfError = 2;

/// Search flags accepted by `lf_db_find_lenses_hd`. Sorts by focal length,
/// removes duplicate lens names, and keeps only the best crop-factor entry —
/// the flag darktable's `lens.cc` passes (`#define LF_SEARCH_SORT_AND_UNIQUIFY
/// 2`; newer lensfun headers renamed it with an `_ECS` suffix, same value).
pub const LF_SEARCH_SORT_AND_UNIQUIFY: i32 = 2;

// ── Correction-selection flags (`enum lfModifyFlags`) ────────────────────────

pub const LF_MODIFY_TCA: i32 = 0x0000_0001;
pub const LF_MODIFY_VIGNETTING: i32 = 0x0000_0002;
pub const LF_MODIFY_DISTORTION: i32 = 0x0000_0008;
pub const LF_MODIFY_GEOMETRY: i32 = 0x0000_0010;
pub const LF_MODIFY_SCALE: i32 = 0x0000_0020;
/// `LF_MODIFY_ALL = ~0` — every correction bit.
pub const LF_MODIFY_ALL: i32 = !0;

// ── Pixel formats & component roles (`lfPixelFormat`, `lfComponentRole`) ─────

/// `LF_PF_F32`: 32-bit floating-point R,G,B — what our f32 buffers use.
pub const LF_PF_F32: i32 = 3;

/// `LF_CR_3(RED, GREEN, BLUE)` — tightly packed RGB, stride 3.
pub const LF_CR_3_RGB: i32 =
    (4 /*RED*/) | (5 /*GREEN*/ << 4) | (6 /*BLUE*/ << 8);
/// `LF_CR_4(RED, GREEN, BLUE, UNKNOWN)` — RGBA where the fourth lane (alpha)
/// must be left untouched by colour modification.
pub const LF_CR_4_RGB_UNKNOWN: i32 =
    (4 /*RED*/) | (5 /*GREEN*/ << 4) | (6 /*BLUE*/ << 8) | (2 /*UNKNOWN*/ << 12);

// ── Projection types (`enum lfLensType`) ─────────────────────────────────────

pub const LF_UNKNOWN: i32 = 0;
pub const LF_RECTILINEAR: i32 = 1;
pub const LF_FISHEYE: i32 = 2;
pub const LF_PANORAMIC: i32 = 3;
pub const LF_EQUIRECTANGULAR: i32 = 4;
pub const LF_FISHEYE_ORTHOGRAPHIC: i32 = 5;
pub const LF_FISHEYE_STEREOGRAPHIC: i32 = 6;
pub const LF_FISHEYE_EQUISOLID: i32 = 7;
pub const LF_FISHEYE_THOBY: i32 = 8;

// ── Opaque handles ───────────────────────────────────────────────────────────

#[repr(C)]
pub struct lfDatabase {
    _opaque: [u8; 0],
}
#[repr(C)]
pub struct lfModifier {
    _opaque: [u8; 0],
}

// ── Data-member prefixes (library-owned objects) ─────────────────────────────

#[repr(C)]
pub struct lfCamera {
    pub Maker: *const c_char,
    pub Model: *const c_char,
    pub Variant: *const c_char,
    pub Mount: *const c_char,
    /// Crop factor relative to 35 mm film; must be defined.
    pub CropFactor: f32,
    /// Match score filled in by `lf_db_find_cameras*`; not a camera property.
    pub Score: i32,
}

#[repr(C)]
pub struct lfLens {
    pub Maker: *const c_char,
    pub Model: *const c_char,
    pub MinFocal: f32,
    pub MaxFocal: f32,
    pub MinAperture: f32,
    pub MaxAperture: f32,
    /// NULL-terminated list of mounts.
    pub Mounts: *mut *const c_char,
    /// Horizontal/vertical shift of the optical centre, −0.5…+0.5.
    pub CenterX: f32,
    pub CenterY: f32,
    /// Crop factor at which the calibration was taken; must be defined.
    pub CropFactor: f32,
    /// Aspect ratio of the calibration images (w/h).
    pub AspectRatio: f32,
    /// `lfLensType` (rectilinear etc.) — opaque to us for now.
    pub Type: i32,
    // Calibration lists (CalibDistortion / CalibTCA / CalibVignetting / …)
    // deliberately not declared yet — bound when a slice consumes them.
}

// ── Database lifecycle & lookup ──────────────────────────────────────────────

extern "C" {
    pub fn lf_db_new() -> *mut lfDatabase;
    /// Loads the database from the standard system locations
    /// (`/usr/share/lensfun`, `/usr/local/share/lensfun`,
    /// `~/.local/share/lensfun`, …). Returns [`LF_NO_DATABASE`] when no
    /// database file could be found — handle that at the call site (an empty
    /// db is legal; missing data files are the usual cause).
    pub fn lf_db_load(db: *mut lfDatabase) -> lfError;
    pub fn lf_db_destroy(db: *mut lfDatabase);

    /// NULL-terminated array allocated by this call; free it (not its
    /// elements, which stay database-owned) with [`lf_free`]. Both name
    /// arguments may be NULL wildcards.
    pub fn lf_db_find_cameras(
        db: *const lfDatabase,
        maker: *const c_char,
        model: *const c_char,
    ) -> *const *const lfCamera;

    /// Home-directory-aware lens search (what darktable's lens.cc calls).
    /// Returns a NULL-terminated list ordered best-score first; free the
    /// array with [`lf_free`].
    pub fn lf_db_find_lenses_hd(
        db: *const lfDatabase,
        camera: *const lfCamera,
        maker: *const c_char,
        lens: *const c_char,
        sflags: i32,
    ) -> *const *const lfLens;

    /// Frees memory allocated by lensfun helpers (returned lists, strings).
    pub fn lf_free(data: *mut core::ffi::c_void);

    /// All cameras in the database, database-owned and NULL-terminated (no
    /// free). Order is the database's own; callers sort/dedupe for display.
    pub fn lf_db_get_cameras(db: *const lfDatabase) -> *const *const lfCamera;

    /// All lenses in the database, database-owned and NULL-terminated (no
    /// free). Includes every mount; filter by `lfLens.Mounts` for a camera.
    pub fn lf_db_get_lenses(db: *const lfDatabase) -> *const *const lfLens;
}

// ── Modifier (per-image correction state) ────────────────────────────────────
//
// `cbool` is lensfun's `#define cbool int`; `lfPixelFormat`/`lfLensType`/
// component-role values are the i32 constants declared above. The modifier is
// created for one image geometry, initialized once, then applied per row —
// apply calls are treated as thread-safe const reads (darktable runs its row
// loops in parallel over a shared modifier).

extern "C" {
    /// Builds a modifier for `lens` at image size `width × height` with crop
    /// factor `crop` (the *camera's* crop; coordinates are expressed on that
    /// normalised film plane). Returns NULL on allocation failure.
    pub fn lf_modifier_new(
        lens: *const lfLens,
        crop: f32,
        width: i32,
        height: i32,
    ) -> *mut lfModifier;
    pub fn lf_modifier_destroy(modifier: *mut lfModifier);

    /// Enables the corrections selected by `flags` (LF_MODIFY_* bits) for
    /// pixel format `format` at shooting parameters focal/aperture/distance.
    /// `targeom` selects projection conversion when LF_MODIFY_GEOMETRY is set;
    /// `reverse` swaps correct↔distort direction. Returns the subset of
    /// `flags` actually enabled (calibration may be missing for some).
    pub fn lf_modifier_initialize(
        modifier: *mut lfModifier,
        lens: *const lfLens,
        format: i32,
        focal: f32,
        aperture: f32,
        distance: f32,
        scale: f32,
        targeom: i32,
        flags: i32,
        reverse: i32,
    ) -> i32;

    /// Scale that keeps the corrected image inside the frame (≥ 1 usually).
    /// Non-const in the header (lensfun.h), though it only reads — keep `*mut`.
    pub fn lf_modifier_get_auto_scale(modifier: *mut lfModifier, reverse: i32)
        -> f32;

    /// Per-channel source-coordinate mapping (TCA + distortion + geometry +
    /// scale). Fills `res` with `width × height` × 6 floats: for each pixel,
    /// (x,y) for R, G, B in that order. Coordinates are absolute image-space.
    pub fn lf_modifier_apply_subpixel_geometry_distortion(
        modifier: *mut lfModifier,
        xu: f32,
        yu: f32,
        width: i32,
        height: i32,
        res: *mut f32,
    ) -> i32;

    /// Per-pixel colour scaling (vignetting). `pixels` points at interleaved
    /// data described by `comp_role` (see [`LF_CR_4_RGB_UNKNOWN`]);
    /// `row_stride` is in **floats** between successive rows.
    pub fn lf_modifier_apply_color_modification(
        modifier: *mut lfModifier,
        pixels: *mut f32,
        x: f32,
        y: f32,
        width: i32,
        height: i32,
        comp_role: i32,
        row_stride: i32,
    ) -> i32;
}
