//! Hand-written FFI bindings to **liblensfun** (the reference C library for
//! lens distortion/TCA/vignetting correction, `pkg-config lensfun`).
//!
//! Kept out of `bindings.rs` on purpose: that file is regenerated by bindgen
//! from `src/common/darktable.h` and knows nothing about lensfun — a
//! regeneration would silently drop anything written there. This module is
//! committed, reviewed, and stable against regeneration.
//!
//! Only the slice of the API the Rust pipeline consumes is declared, mirroring
//! what `src/iop/lens.cc` uses. Structs carry the data-member prefix of the C
//! definitions (the trailing C++ methods occupy no storage); the library
//! allocates every object we touch, so a shorter Rust mirror of a longer C
//! struct is safe for prefix reads.
//!
//! Data model notes:
//! - Returned lists (`lf_db_find_cameras*`, `lf_db_find_lenses_hd`) are
//!   NULL-terminated arrays allocated by each call and released by the caller
//!   with [`lf_free`] — free the *array* only, never the elements, which stay
//!   owned by the database.
//! - `lfMLstr` fields are plain `char *` (the multi-language machinery is a
//!   C++-side convenience).

#![allow(non_snake_case, non_camel_case_types)]

use std::ffi::c_char;

/// `enum lfError`: LF_NO_ERROR == 0. Positive values are the enum codes below;
/// negative return values from lensfun entry points are `-errno`.
pub type lfError = i32;

/// No error occurred (`LF_NO_ERROR`).
pub const LF_NO_ERROR: lfError = 0;

/// Wrong XML data format (`LF_WRONG_FORMAT`, enum value 1).
pub const LF_WRONG_FORMAT: lfError = 1;

/// No database could be loaded (`LF_NO_DATABASE`, enum value 2) — the usual
/// result of missing data files rather than a hard failure for us.
pub const LF_NO_DATABASE: lfError = 2;

/// Search flags accepted by `lf_db_find_lenses_hd`. Sorts by focal length,
/// removes duplicate lens names, and keeps only the best crop-factor entry —
/// the flag darktable's `lens.cc` passes (`#define LF_SEARCH_SORT_AND_UNIQUIFY
/// 2`; newer lensfun headers renamed it with an `_ECS` suffix, same value).
pub const LF_SEARCH_SORT_AND_UNIQUIFY: i32 = 2;

// ── Opaque handles ───────────────────────────────────────────────────────────

#[repr(C)]
pub struct lfDatabase {
    _opaque: [u8; 0],
}
#[repr(C)]
pub struct lfModifier {
    _opaque: [u8; 0],
}

// ── Data-member prefixes (library-owned objects) ─────────────────────────────

#[repr(C)]
pub struct lfCamera {
    pub Maker: *const c_char,
    pub Model: *const c_char,
    pub Variant: *const c_char,
    pub Mount: *const c_char,
    /// Crop factor relative to 35 mm film; must be defined.
    pub CropFactor: f32,
    /// Match score filled in by `lf_db_find_cameras*`; not a camera property.
    pub Score: i32,
}

#[repr(C)]
pub struct lfLens {
    pub Maker: *const c_char,
    pub Model: *const c_char,
    pub MinFocal: f32,
    pub MaxFocal: f32,
    pub MinAperture: f32,
    pub MaxAperture: f32,
    /// NULL-terminated list of mounts.
    pub Mounts: *mut *const c_char,
    /// Horizontal/vertical shift of the optical centre, −0.5…+0.5.
    pub CenterX: f32,
    pub CenterY: f32,
    /// Crop factor at which the calibration was taken; must be defined.
    pub CropFactor: f32,
    /// Aspect ratio of the calibration images (w/h).
    pub AspectRatio: f32,
    /// `lfLensType` (rectilinear etc.) — opaque to us for now.
    pub Type: i32,
    // Calibration lists (CalibDistortion / CalibTCA / CalibVignetting / …)
    // deliberately not declared yet — bound when a slice consumes them.
}

// ── Database lifecycle & lookup ──────────────────────────────────────────────

extern "C" {
    pub fn lf_db_new() -> *mut lfDatabase;
    /// Loads the database from the standard system locations
    /// (`/usr/share/lensfun`, `/usr/local/share/lensfun`,
    /// `~/.local/share/lensfun`, …). Returns [`LF_NO_DATABASE`] when no
    /// database file could be found — handle that at the call site (an empty
    /// db is legal; missing data files are the usual cause).
    pub fn lf_db_load(db: *mut lfDatabase) -> lfError;
    pub fn lf_db_destroy(db: *mut lfDatabase);

    /// NULL-terminated array allocated by this call; free it (not its
    /// elements, which stay database-owned) with [`lf_free`]. Both name
    /// arguments may be NULL wildcards.
    pub fn lf_db_find_cameras(
        db: *const lfDatabase,
        maker: *const c_char,
        model: *const c_char,
    ) -> *const *const lfCamera;

    /// Home-directory-aware lens search (what darktable's lens.cc calls).
    /// Returns a NULL-terminated list ordered best-score first; free the
    /// array with [`lf_free`].
    pub fn lf_db_find_lenses_hd(
        db: *const lfDatabase,
        camera: *const lfCamera,
        maker: *const c_char,
        lens: *const c_char,
        sflags: i32,
    ) -> *const *const lfLens;

    /// Frees memory allocated by lensfun helpers (returned lists, strings).
    pub fn lf_free(data: *mut core::ffi::c_void);
}
